title: bcobb.net
name: bcobb.net
description: >-
  Brian Cobb writes about stuff.
url: "https://www.bcobb.net"
permalink: "/:title/"
collections:
  singletons:
    output: false

markdown: kramdown
kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo

plugins:
  - jekyll-feed
  - jekyll-assets

assets:
  sources:
    - _assets/css
    - _assets/images

exclude:
  - Gemfile
  - Gemfile.lock
  - bin/
  - README
  - log/
  - tmp/
  - bcobb/
  - vendor/
