name: bcobb.net
description: Brian Cobb writes about stuff.
url: http://www.bcobb.net
path: "/"
exclude:
  - Gemfile
  - Gemfile.lock
  - bin/
  - README
  - log/
markdown: redcarpet
permalink: "/:title/"
gems:
  - jekyll-sitemap
  - jekyll-assets
redcarpet:
  extensions:
    - footnotes
    - smart
assets:
  assets:
    - "*.css"
