name: bcobb.net
description: Brian Cobb writes about stuff.
url: https://www.bcobb.net
path: "/"
exclude:
  - Gemfile
  - Gemfile.lock
  - bin/
  - README
  - log/
  - tmp/
  - bcobb/
markdown: redcarpet
permalink: "/:title/"
gems:
  - jekyll-sitemap
  - jekyll-assets
redcarpet:
  extensions:
    - footnotes
    - smart
assets:
  assets:
    - "*.css"
    - "*.svg"
    - "*.png"
collections:
  singletons:
    output: true
