name: bcobb.net
description: Brian Cobb writes about software.
url: http://www.bcobb.net
exclude:
  - Gemfile
  - Gemfile.lock
  - bin/
  - README
markdown: redcarpet
gems:
  - jekyll-sitemap
redcarpet:
  extensions:
    - footnotes
    - smart
